### ISSUE TITLE
Can not find Openpose Python API. 

### ISSUE THREAD

**Issue by xiehaizheng** [open-mmlab/mmskeleton#258]
Thank you for your work. Could you help me with this problem when trying demo?
python main.py demo  --video '/home/wang/mmskeleton/resource/media/skateboarding.mp4' --openpose '/home/wang/openpose/build' --device 0
Can not find Openpose Python API.

**Comment by DeH40** [comment]
i have the same problem，have you worked out?

**Comment by DeH40** [comment]
i worked it out .when you make install the openpose , choose the option "BUILD_PYTHON" in cmake .

**Comment by starry-night-0** [comment]
Hi,
Did you install it in win10 or others?

**Comment by xiehaizheng** [comment]
> Hi,
> Did you install it in win10 or others?

ubuntu

**Comment by yosagaf** [comment]
Hi,

I'm getting the same error, I installed open pose and choose the option "BUILD_PYTHON" in cmake-gui and command line but still getting the same error don't know why.
I'm using this command "python3 main.py demo --video /home/can/actions/st-gcn/videos/video.mp4 --openpose /home/can/actions/st-gcn/openpose/build --device 1
Any suggestion, I tried ls ../python/openpose and cannot see .so files

**Comment by 38weiying** [comment]
> 我解決了。當您安裝openpose時，在cmake中選擇“ BUILD_PYTHON”選項。

i use this, but still have the same problem
what should i do?

**Comment by 38weiying** [comment]
> 你好
> 
> 我正在使用ubuntu18.04，我遇到了相同的錯誤，我安裝了開放姿勢並在cmake-gui和命令行中選擇了選項“ BUILD_PYTHON”，但仍然收到相同的錯誤，不知道為什麼。
> 我正在使用此命令“ python3 main.py演示--video /home/can/actions/st-gcn/videos/video.mp4 --openpose / home / can / actions / st-gcn / openpose / build-設備1
> 任何建議，我嘗試了ls ../python/openpose，但看不到.so文件



> i worked it out .when you make install the openpose , choose the option "BUILD_PYTHON" in cmake .

i use this, but still have the same problem
what should i do?

**Comment by 38weiying** [comment]
> Hi,
> 
> I'm using ubuntu18.04 I'm getting the same error, I installed open pose and choose the option "BUILD_PYTHON" in cmake-gui and command line but still getting the same error don't know why.
> I'm using this command "python3 main.py demo --video /home/can/actions/st-gcn/videos/video.mp4 --openpose /home/can/actions/st-gcn/openpose/build --device 1
> Any suggestion, I tried ls ../python/openpose and cannot see .so files

I also choose the option "BUILD_PYTHON" when install the openpose , but still have the same problem
Do you solve the problem?

**Comment by 38weiying** [comment]
### hi, guys! I found my solution!!!
this work in ubuntu 18.04
I reference this article>>https://medium.com/@erica.z.zheng/installing-openpose-on-ubuntu-18-04-cuda-10-ebb371cf3442
_**i use part 1/step 4 to install caffe**_
configure & building again
then everything go well

i install stgcn about 6 months......i really felt frustrated these months
so, i hope everyone can also go well!

**Comment by zjr666** [comment]
> 
> ### hi, guys! I found my solution!!!
> 
> this work in ubuntu 18.04
> I reference this article>>https://medium.com/@erica.z.zheng/installing-openpose-on-ubuntu-18-04-cuda-10-ebb371cf3442
> _**i use part 1/step 4 to install caffe**_
> configure & building again
> then everything go well
> 
> i install stgcn about 6 months......i really felt frustrated these months
> so, i hope everyone can also go well!
> if you think this solve your problem, tell me~i wanna know! thanks

Can you share the specific steps with me?    I can't access this website.

**Comment by 38weiying** [comment]
> > ### hi, guys! I found my solution!!!
> > this work in ubuntu 18.04
> > I reference this article>>https://medium.com/@erica.z.zheng/installing-openpose-on-ubuntu-18-04-cuda-10-ebb371cf3442
> > _**i use part 1/step 4 to install caffe**_
> > configure & building again
> > then everything go well
> > i install stgcn about 6 months......i really felt frustrated these months
> > so, i hope everyone can also go well!
> > if you think this solve your problem, tell me~i wanna know! thanks
> 
> Can you share the specific steps with me? I can't access this website.

![image](https://user-images.githubusercontent.com/45616986/96331000-31afc200-108c-11eb-981d-0a9bd3b79597.png)

**Comment by G-Apple1** [comment]
I have the same problem ，this work in win10，how can I work out？
I also don't know why the openpose Python API is used ?

![image](https://user-images.githubusercontent.com/62458945/103357878-36aeda00-4aef-11eb-9712-9241fa674ad2.png)

**Comment by ChenYingin** [comment]
我也有同样的问题哎

**Comment by ZhaoYu810** [comment]
我试着解决了，主要就是把命令中的python main.py demo改成python main.py demo_old。
希望我焦虑了很久的经验能对你有所帮助（哭）

**Comment by Fasydeer** [comment]
Hi, guys! I solved the problem I encountered in ubuntu and can run demo_realtime and demo_offline.
Can not find Openpose Python API，which is caused by an Openpose compilation error. run
 `ls -l /usr/bin/python` 
and check where your python is pointing, if your python points to python2, run
 `sudo rm /usr/bin/python` 
`sudo ln -s /usr/bin/python3 /usr/bin/python`
then CMake and Compilation your openpose again.
`ls usr/bin/python/openpose`
Check the contents of this location. It should contain one of the following file:
`pyopenpose.cpython-35m-x86_64-linux-gnu.so`
Then the API problem is solved.
Next I encountered the following problem.
#384
